baseURL = 'https://dlitescript.com'
languageCode = 'en-US'
title = 'DLiteScript'
theme = 'plume'

disableHugoGeneratorInject = true
disableKinds = ['taxonomy', 'term']
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
newContentEditor = 'nvim'
printI18nWarnings = true
printUnusedTemplates = true

[params]
  shortName = 'DLiteScript'
  description = 'DLiteScript is a delightfully simple scripting language with syntax inspired by Go, among other languages. Easy to learn, powerful error handling, and comprehensive tooling.'
  keywords = 'DLiteScript, scripting language, programming, Go, statically typed'
  author = 'DLiteScript'
  backgroundColor = '#0a0a0a'
  themeColor = '#60a5fa'
  repositoryContentDir = 'https://github.com/Dobefu/DliteScript/tree/main/docs/content'
  showEditLink = true

  [params.socialLinks]
    github = 'https://github.com/Dobefu/DLiteScript'

[menus]
  [[menus.main]]
    name = 'Playground'
    pageRef = '/playground'
    weight = 20

  [[menus.main]]
    name = 'Documentation'
    pageRef = '/docs'
    weight = 30

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[sitemap]
  changefreq = 'monthly'
  priority = 0.5
  filename = 'sitemap.xml'

[outputFormats]
  [outputFormats.sitemap]
    mediaType = 'application/xml'
    baseName = 'sitemap'
    notAlternative = true

[outputs]
  home = ['html', 'rss', 'webappmanifest', 'json']

[security]
  [security.exec]
    allow = ['^go$', '^git$', '^nvim$']

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

  [markup.highlight]
    lineNos = true
    noClasses = false

  [markup.goldmark]
    [markup.goldmark.extensions]
      strikethrough = false

      [markup.goldmark.extensions.extras]
        delete.enable = true
        mark.enable = true
        insert.enable = true
        subscript.enable = true
        superscript.enable = true

      [markup.goldmark.extensions.passthrough]
        enable = true

        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]']]
          inline = [['\(', '\)']]

